### ISSUE TITLE
Support for presenting any Input/Output data assigned to a Task??

### ISSUE THREAD

**Issue by proth1** [viadee/camunda-modeler-tooltip-plugin#14]
This tooltip plug-in is outstanding.  Any chance it could be extended to support Input/Output mappings?  I would love to help if considered a good idea.  Thank you for your kind consideration.

**Comment by rnschk** [comment]
Hi @proth1, thank you very much, I'm always happy when some Modeler-users out there use the Tooltip-plugin! 😊 
  
Concerning your Input-/Output-idea: Technically, this shouldn't be a problem. As I started this plugin, I also experimented around with different properties to be included within the tooltips. Finally, I came to the conclusion, that I didn't want to provide redundant information which might be already covered by other plugins, e.g. the Transaction-Boundaries-Plugin, or the Property-Info-Plugin.
What exactly do you expect to be shown: A marker, that there are IO-Mappings, or do you mean the concrete mappings in details?
  
BR rnschk

**Comment by proth1** [comment]
Thank you, @rnschk.  Sorry for my delay in getting back to you.
Yes, I would want to see the actual mappings, if there are any.

**Comment by rnschk** [comment]
Ok, I understand, and I can try to add this feature, but I can't promise when it will happen. 🙈 At first glace it might seem simple, but I just had a brief look at the I/O-mapping oppertunities. There are at least four different types of mapping, namely: `List`, `Map`, `Script`, `String or expression`, which all have different settings and partially even with a variable amount of entries. This might be tricky to be arranged in a clear and structerd way: 

![io-mappings](https://user-images.githubusercontent.com/5700718/175331833-c2cb0ddd-3163-4abc-8c2b-724942e281ef.gif)

**Comment by proth1** [comment]
Thank you very much @rnschk.  As an MVP I think there would be significant value provided by initially just indicating that there is or is not any input/output settings for a given activity.  Maybe a view like the following without the complexity of displaying the lower-level details.
![image](https://user-images.githubusercontent.com/20020726/175335051-aba2ba0e-1719-4991-a5b7-3613defd2e83.png)

**Comment by rnschk** [comment]
Happy new year! 🎉   

Hooray, finally, I found some time to include input/output-mappings in the tooltip-infos, yeah! At least some basic properties are shown now, if the mapping is of type string or expression, otherwise only the mapping-type is shown (see screenshot).

![image](https://user-images.githubusercontent.com/5700718/210262324-7440b5b1-16fa-4132-aa19-1a0a424e64ee.png)

BR rnschk

**Comment by proth1** [comment]
@rnschk, this is really amazing!!  I love it!!! 
Thank you so much!!!
What an amazing new year present.
Happy New Year!!!
